language: php

sudo: required

branches:
  only:
    - master

php:
  - 7.1

env:
  global:
    - COVERAGE=false
  matrix:
    - MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli MOODLE_PLUGIN_CI
    - MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql MOODLE_PLUGIN_CI
    - MOODLE_BRANCH=master DB=mysqli MOODLE_PLUGIN_CI
    - MOODLE_BRANCH=master DB=pgsql MOODLE_PLUGIN_CI

before_install:
  - phpenv config-rm xdebug.ini

script:
  - moodle-plugin-ci behat